name: Deploy RAG to HuggingFace

on:
  push:
    branches: [HF-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub CI"

      - name: Clone Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://A7medAyman:$HF_TOKEN@huggingface.co/spaces/A7medAyman/RAG hf_space

      - name: Copy src to HF Space
        run: |
          cp -r src/. hf_space/

      - name: Commit & Push to HF Space
        run: |
          cd hf_space
          git add .
          # Only commit if there are changes
          git diff --cached --quiet || (git commit -m "Deploy from GitHub: ${{ github.sha }}" && git push)